apiVersion: v1
kind: PersistentVolume
metadata:
  name: files-pv
  namespace: directory-synchronizer-backend
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/local-storage"