apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
  namespace: directory-synchronizer-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard